### ISSUE TITLE
CircularReferenceException with Gradle 5.6 (Nightly)

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#154]
using this sample project
https://github.com/cdietrich/gradle_issue_9674
 with the latest gradle nightly

` ./gradlew wrapper --gradle-version=5.6-20190629000108+0000` 
`./gradlew clean build`

it will complain about a cyclic dependency

```
./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:classes
\--- :compileJava
     \--- :generateXtext
          \--- :classes (*)

(*) - details omitted (listed previously)

```

@oehme do you have any idea what could cause this?

https://scans.gradle.com/s/4qqs3qwxho4vk

**Comment by cdietrich** [comment]
@oehme can it be this is a follow up error on https://github.com/xtext/xtext-gradle-plugin/issues/124
(have no idea where to put which annotations there)

**Comment by cdietrich** [comment]
i tried to find out what could cause this but did not find any clue. since  @oehme does not seem to be responding i created https://discuss.gradle.org/t/new-task-cycle-with-gradle-5-6-nightly/32262 in the hope to get more hints

**Comment by cdietrich** [comment]
i think i at least have a hint

we do something like that:

   `generatorTask.classesDirs = generatorTask.classesDirs ?: javaSourceSet.output.classesDir`

    mark

    `@Accessors @Input @Optional FileCollection classesDirs`

=> but why is this considered a cycle if we just copy over stuff

**Comment by cdietrich** [comment]
maybe it should be `generatorTask.classesDirs = generatorTask.classesDirs ?: javaSourceSet.output.dirs`

**Comment by cdietrich** [comment]
hmmm indeed the values are different.
but how can i then read the classesDirs without installing a cycle.
or shall we introduce a second property for internal use.
or will that be traced too.

or is the general problem that we in fact have a cycle e.g for install debug info

**Comment by cdietrich** [comment]
so removing the `@Input` or creating a second collection with no `@Input` seems to help but i have the feeling this just covers the problem

**Comment by oehme** [comment]
The classes dir should not be an input. In fact, it doesn't conceptually belong to the `XtextGenerate`  task at all. It is used to install debug info at the end of the `compileJava` task.

The simplest fix is removing that annotation. Also, we should not be instrumenting all classes dirs at the end of javaCompile, only `javaCompile.destinationDir`, since the other classes directories might not even be created at that point.

**Comment by cdietrich** [comment]
for the first part: so the classesDir should not be settable from outside at all?

hmm i did not get the second part.

**Comment by oehme** [comment]
The whole `installDebugInfo` method doesn't belong on the `XtextGenerate` class, it should be in its own class. It is an action that runs as part of `JavaCompile`, see [here](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtextBuilderPlugin.xtend#L165).

We should only instrument the javaCompile.destinationDir, since that's what JavaCompile creates and that's the only task we hook into. The other classesDirs are created by other tasks like GroovyCompile, which our plugin simply doesn't handle.

**Comment by cdietrich** [comment]
hmmm i still dont understand what you mean by "instrument"
=> will to a pr for the `@Input` but still have no idea what to change besides that

**Comment by cdietrich** [comment]
@oehme where you thinking about something like this one: https://github.com/xtext/xtext-gradle-plugin/compare/cd_issue154new

**Comment by oehme** [comment]
Yes, that looks great.
