### ISSUE TITLE
Gradle Deprecations

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#160]
With Gradle 6.x you will get the following deprecations

```
Property 'bootstrapClasspath' has @Input annotation used on property of type 'FileCollection'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'languages' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sourceSetOutputs' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sources' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

we need to find fixes / replacements for these

**Comment by cdietrich** [comment]
@oehme do you have some hints on how to fix these?

**Comment by oehme** [comment]
- `classpath`, `xtextClasspath` and` bootstrapClasspath` should be annotated `@Classpath`
- `languages` should be annotated `@Nested` and then all its relevant properties should be annotated with `@Input` and `@Nested` as well. So far we weren't tracking changes to any of those properties, which was wrong. This was due to limitations in older Gradle versions which didn't support `@Nested` lists/maps.
- `sourceSetOutputs` and `sources` should be marked `@Internal`, as they are already indirectly tracked by `getMainSources` and `getOutputDirectories`

**Comment by cdietrich** [comment]
> This annotation should be attached to the getter method in Java or the property in Groovy. Annotations on setters or just the field in Java are ignored.

**Comment by cdietrich** [comment]
there are some more

```
> Task :org.xtext.example.mydsl:xtextEclipseSettings
Property 'languages' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sourceSets' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

```

**Comment by cdietrich** [comment]
@oehme any hints?

**Comment by oehme** [comment]
The sourceSets are just there to compute the input and output files, which are already tracked via derived getters. So the sourceSet list can be marked as `@Internal`. The languages on the other hand need to have their properties tracked (e.g. the name of their standalonesetup etc.).

**Comment by oehme** [comment]
Closing this since all deprecation warnings were fixed and I've added logic to the integ tests that will make them fail on any deprecations. We just need to bump up the "latestXtextVersion" to find out.

There are some deprecated methods used in the code, but none of them are fixable at this point without breaking compatibility with older Gradle versions. These methods are marked deprecated, but Gradle doesn't actually warn about them at runtime, because too much still depends on them (even inside Gradle itself). However, it will happen at some point, and then we'll have to finally break compatibility. That'll be a good point to also give the plugin an overall refresh, e.g. using Gradle's `Provider` API for the DSL, the worker API for our classloader isolation etc. This would simplify this plugin a lot.
