### ISSUE TITLE
Allow specifying file extension per language

### ISSUE THREAD

**Issue by oehme** [xtext/xtext-gradle-plugin#2]
If we know the file extension of each language, we can filter unrelated changes during incremental builds.

**Comment by vorburger** [comment]
@oehme I've just noticed something related to this which I'm not sure you've done intentionally?

Using plugins { id "org.xtext.builder" version "1.0.0-RC1" } I've initially been struggling with:

    Skipping task ':examples/ch.vorburger.examples.xeemim.pizzas:generateXtext' as it has no source files.

until I gathered that it's not optional but that I *HAVE* to use:

    fileExtension = 'x' 
    // the file extension for your language.
    // Equal to the language's name by default
        
To me, this seems a "bug" - because via *StandaloneSetup Injector you probably can somehow obtain the language @Names.named(Constants.FILE_EXTENSIONS) @Inject String?

Or is there something to do with Gradle lazy initialization here that you need to be able to filter BEFORE loading the StandaloneSetup?

**Comment by oehme** [comment]
@vorburger  the documentation states that the file extension is equal to the language name by default, but you can override it. I guess that is too far down on the page and should be part of the first example.

Running the StandaloneSetup every time just to find out the file extension would be very bad for build performance. That is why it has to be configured.

**Comment by vorburger** [comment]
@oehme I've raised PR https://github.com/xtext/xtext-gradle-plugin/pull/30 with a one line addition to make this clear in the first example

**Comment by oehme** [comment]
This is now part of 1.0.0
