### ISSUE TITLE
More Gradle 7.5/7.6 deprecations

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-gradle-plugin#207]
val java = project.convention.findPlugin(JavaPluginConvention)
seems to be deprecated
did not find anything useful in the release notes
https://docs.gradle.org/7.5-rc-1/userguide/upgrading_version_7.html#all_convention_deprecation
@oehme what is the replacement?

`project.getExtensions().getByType(JavaPluginExtension)` ?

`https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginExtension.html#getSourceSets--`
seems to be a gradle 7 feature

conventionMapping seems to be deprecated too 
https://docs.gradle.org/7.5-rc-1/userguide/upgrading_version_7.html#convention_mapping

**Comment by oehme** [comment]
The `JavaPluginConvention` deprecation is not a big deal. We can check the current Gradle version and then use the appropriate method call. That way we can still support older versions. 
The deprecation of convention mapping means we have to finally move to a `Property`-based API. This actually fits well with the minimum version bump to 5.x, because the `Property` API has been mature since that time.

I'll look into it on a free weekend.

**Comment by cdietrich** [comment]
TODO:check if there is more problems with Gradle 7.6

**Comment by cdietrich** [comment]
@oehme any chance you can look into this in combination with https://github.com/xtext/xtext-gradle-plugin/pull/204

**Comment by cdietrich** [comment]
@oehme any chance you find some time to look into this?
