### ISSUE TITLE
Executing registration steps before xtext-gradle-plugin

### ISSUE THREAD

**Issue by ujhelyiz** [xtext/xtext-gradle-plugin#26]
As a follow-up from https://www.eclipse.org/forums/index.php?t=rview&goto=1711227#msg_1711227, I open this issue to detail. I am sorry if I am not entirely clear, as both I and the other members of the IncQuery team have only a very limited experience with gradle.

Basically, the code generator of EMF-IncQuery requires some user-defined EPackages available that are not referenced by class. In case of the maven compiler, we provide a plug-in that reads some configuration information and registers the EPackages accordingly, then simply delegates the delegation phase to the xtext-maven-compiler (see http://git.eclipse.org/c/incquery/org.eclipse.incquery.git/tree/maven/incquery-maven-plugin/src/main/java/org/eclipse/incquery/maven/incquerybuilder/IncqueryBuilderMojo.java for details).

The question is whether (1) it is required to do something like that for the grade plugin, or is it possible to do something with the scripting API? Or if not, (2) what do we need to do to allow the code generation work in case of gradle as well?

**Comment by oehme** [comment]
Thanks for following up on this =) I've been thinking about your use case and I think it can be solved at a more general level than Maven/Gradle (so that you could get rid of your special Maven Plugin if you want):

You could use a [ServiceLoader](https://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) to look up implementations of "EPackageContributor" (or whatever you want to call it) on the classpath. Your users just have to implement that interface and the IncQuery StandaloneSetup could pick them up and register the returned EPackages.

Alternatively you could tell the user to put some config file into some well known location and read that file during StandaloneSetup.

Or you could look for all plugin.xml's on the classpath and read the "registeredEPackage" extension point information from them.

Would any of these work for you?

If these options don't work, we could add hooks to the Gradle plugin that allows you to call arbitrary code before invoking the builder. But I'd only want to do that if it's the only remaining option.

**Comment by ujhelyiz** [comment]
To tell the truth, for now I am looking for a simple solution for Gradle, as it seems some of our users want that, although it is not very high on our current priority list... :) In the longer term, I don't think we are planning to get rid of the maven plug-in (and might introduce a gradle plug-in if required).

The ServiceLoader approach might work, especially if we could provide some parameters from the build configuration, I guess that would be a very nice solution, e.g. we could provide a few generic implementations for the common cases. However I am not entirely familiar with this functionality of Java, but it seems promising. Do you know of anyone who uses this approach to look for some inspiration?

I don't really like the idea of the fixed configuration file, albeit we already have one for cases when the IDE settings are wrong (e.g. we have found that sometimes the generated EPackage declaration is not entirely correct, but couldn't change the models), so this could also work. However, we try to give the impression that this fallback file is usually unnecessary.

Reading the plugin.xml files is a direction I really don't want to take (especially that we have seen not entirely correct declarations), but the other two options might work. I understand that arbitrary code execution is not really something you want to support - that could cause issues. If it comes to that, we will provide our own Gradle plug-in as well.

**Comment by oehme** [comment]
The problem with providing your own plugin (both Maven and Gradle) is that you can no longer cross-reference between IncQuery and other Xtext languages. That kind of defeats the purpose of being an Xtext language ;)

Adding arbitrary code execution is by no means a "simple solution", because it would needs a lot of classloader magic (Xtext runs in an isolated classloader in Gradle). That's why it would be my last resort.

The ServiceLoader approach is very simple, the JavaDoc basically says it all: You define an interface with one method called  `getRegistreredEPackages` and your clients implement it and register it in the Meta-Inf folder. 

Regarding the config file: I didn't mean a fixed one, but one in the user's project director.

**Comment by ujhelyiz** [comment]
Cross-referencing is an issue we have not considered yet, but it is a good point. Sadly, we have some internal design issues we have to iron out before. We know what to do, but it requires time and effort to maintain compatibility as much as possible. :) And yes, we could make cross-language references work with adding extra language options to the incquery-maven-compiler, and then forwarding that as well to the xtext-compiler, but that would be really strange for the end users. :)

I have absolutely no problem with not supporting arbitrary code execution - I would also be against it if I have to support it. :)

About ServiceLoaders, I see they are really similar to OSGi service access, just I don't understand correctly how this registration works with maven/gradle, what has the user to configure, but I have to experiment a bit, because it might be a better way to go in the long run.

About config file, I understood what you meant, thanks.

Altogether, thank you for the detailed answers, I will look into the options and come back with the results.

**Comment by oehme** [comment]
ServiceLoaders are not Maven/Gradle specific, it works like this:

Carl wants to to use IncQuery with the additional EPackage `com.carls.World`. So he creates an implementation of `incquery.EPackageProvider` that returns this name. He puts that class into his jar file along with the descriptor in the Meta-Inf directory.

Now when he uses the Gradle/Maven (or any other standalone) compiler, he just adds his jar to the classpath. Your ServiceLoader discovers it and registers the `com.carls.World` package .

**Comment by oehme** [comment]
I'll close this, as there are several approaches that work better than adding arbitrary callbacks. Most importantly, arbitrary callbacks are not serializable and so could not participate in up-to-date checks, which would be really confusing to users.
