### ISSUE TITLE
xtend-gen source folder confusion

### ISSUE THREAD

**Issue by otrosien** [xtext/xtext-gradle-plugin#42]
Something I already noticed in this issue https://github.com/oehme/xtend-contrib/pull/34 : There seems to be a confusion in how the xtend plugin registers its xtend-gen folder as source folders in eclipse. 

I have a small toy project using xtend where this can be reproduced: https://github.com/otrosien/spring-boot-xtend-demo

context:
- java 1.8.0_72, 
- gradle 2.11, 
- eclipse mars.1, 
- buildship 1.0.9.v20160211, 
- xtext & xtend 2.9.1 installed in eclipse

Observed behaviour:
- a clean workspace and a clean gradle project (without .classpath, .project build bin and xtend-gen folders) imports using "Import project" ... > "gradle project" in a way that xtend registers its output folders using src/{main,test}/xtend-gen
- after a "gradle assemble" from command-line (+F5 in the IDE) eclipse also shows "build/xtend/{main,test}" as source folders, but actually gives the illusion that they are empty -- probably due to buildship generally trying to hide the contents of the "build" directory from the user.
- sometimes later, but not easily reproducible, eclipse complains about missing source folders, when gradle is working on the build folder on the command-line

Desired behaviour:
- eclipse- and gradle-based xtend-gen should not interfer with each other.

**Comment by oehme** [comment]
The desired behavior is that Eclipse and Gradle use the same folder: The one defined in the Gradle build. This is a limitation in Buildship. It already works correctly when using `gradle eclipse`.

**Comment by otrosien** [comment]
@oehme what if I want eclipse to put the output into a different folder than gradle?

**Comment by oehme** [comment]
That's not possible at the moment. And I don't really see the trouble with CLI vs. Eclipse. Given the same configuration, they will produce the same output. The bin vs. build situation is a little different, because in general you cannot make Eclipse mimic the Gradle build 100%. But for Xtend we can.

**Comment by otrosien** [comment]
Sorry for being so picky, but I'm not convinced yet ;-)

a) I don't want eclipse to run into compile errors when I issue gradle clean. Beware that eclipse is also having its filesystem caching layer of the workspace, so what you see there usually is not up-to-date when you have external processes changing things

b) I don't want gradle to fail or getting the false assumption it's up-to-date because eclipse is in the process of writing to build/xtend-gen

My understanding is, that both expect to be the only one managing this generated folder, so why would you want to have two processes sharing it? Disk space? Faster turnaround of the compile task? Possibility to switch off the xtend compilation in eclipse in the future? And where is the so-called confusion of the user if they produce independent output? I really don't see it.

So sum it up, "given the same configuration [..]" is the actually the main driver of confusion: The xtend-plugin needs _enforce_ the same settings in eclipse and gradle, e.g. by  disabling the eclipse settings dialog. If that's done, it could be completely transparent to the user, that gradle is writing somewhere else.

**Comment by otrosien** [comment]
What if xtend in the IDE is a different version than xtend in gradle? Don't you think this can become a problem, too?

**Comment by oehme** [comment]
Wow, I wrote a pretty long response to this some time ago and it seems I either never pressed "submit" or it got lost. I'll try to recollect my thoughts:

> I don't want eclipse to run into compile errors when I issue gradle clean.

If you do a clean without a rebuild in Eclipse, you also see compile errors, so I don't know what the difference there is.

> when you have external processes changing things

If you invoke Gradle through Buildship, you won't have this problem

> eclipse is in the process of writing to build/xtend-gen

When does this happen? 

> why would you want to have two processes sharing it?

Because most users fully expect this. They don't want to keep two different locations in mind when thinking about "where are the generated Java files, in case I want to look at them?". Also, having different source folders in Eclipse than in Gradle would require postprocessing of the classpath XML (removing source folders that Gradle added before).

> What if xtend in the IDE is a different version than xtend in gradle?

You should always use the Xtend plugin that matches whatever Xtend library version you have on the classpath. I know Xtend has become more stable in that regard, but it is still highly recommended.

**Comment by otrosien** [comment]
So, finally I see the problem: "... having different source folders in Eclipse than in Gradle would require postprocessing of the classpath XML (removing source folders that Gradle added before)."

As gradle exports its source folders to eclipse, and build/xtend-gen is added as source folder, it would end up showing up in eclipse in addition to eclipse's own src/xtend-gen.

So, in either way, hiding build/xtend-gen from eclipse, or stopping eclipse to use its own src/xtend-gen, this needs solving. How you solve it may not such a big difference in the end, and maybe/hopefully my concerns are only problems in theory. :-)  Has it been filed at Buildship yet?

**Comment by oehme** [comment]
You could follow https://bugs.eclipse.org/bugs/show_bug.cgi?id=473062

The topic is deliberately vague because there are several possible
solutions and we don't want people to get excited for one or the other ;)
Am 18.03.2016 18:17 schrieb "Oliver Trosien" <notifications@github.com>:
