### ISSUE TITLE
Error when using Xtend for testCompile only

### ISSUE THREAD

**Issue by gunther-bachmann** [xtext/xtext-gradle-plugin#65]
Within a java project I want to use xtend just for tests. My build.gradle (excerpt) looks like this:

```
plugins {
    id 'org.xtext.xtend' version '1.0.12'
}

repositories {
    jcenter()
}

dependencies {
    testCompile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0'
}
```

When building, the task :generateXtext fails (classpath issue when trying to determine the xtext version, so it seems).
I added `generateXtext.enabled = false`, but that did not really help (fails in compileJava).
Adding the dependency as `compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0'` works fine but is not what I want.
Any suggestions?

**Comment by oehme** [comment]
We need to skip the task if there are no "real" DSL input files. We consider .java files an input, because we link against them. But if there are only .java files we should skip the task. Similarly we should skip the bytecode enhancement if no work was done.

We should have a general solution for this, so users can mark a language as "provides references only" (need a better name here).

**Comment by franzbecker** [comment]
As a workaround one can explicitly set the Xtext version and disable the generateXtext task:

	xtext.version = "2.9.0"
	generateXtext.onlyIf { false }

Just skipping the task if there is no "real" DSL input won't work here as the compileJava task will fail during dependency resolution with: *Could not infer Xtext classpath, because xtext.version was not set and no xtext libraries were found on the configuration ':compileClasspath' classpath*

I'm not sure what the best solution would be. We could do the following:

- If `xtext.version` is set, add `XtextGenerate` tasks for all source sets
- If not set, add `XtextGenerate` tasks only for source sets that have an Xtext dependency on their respective class path

It could also be useful to restrict the source sets the Xtext plugin is applied to. I didn't find a way to do that in the current implementation - maybe I missed something there.

What do you think? Any other ideas?

**Comment by oehme** [comment]
The solution is to mark `Language`s that are only used for linking. Then put an `@IgnoreWhenEmpty` file collection on the task which only contains source files from languages which are actually used for generation.

**Comment by oehme** [comment]
Actually, we already have the needed info: When a language has no outlets, then it should not be considered for "skipWhenEmpty". I've [split the task's inputs](https://github.com/xtext/xtext-gradle-plugin/commit/8f6068e3efb1daea90212c878dd2c532a5a5f195) into "main sources" and "all sources" to reflect that and added a test for @gunther-bachmann's use case.
