### ISSUE TITLE
Xtend: Ability to suppress warnings in gradle build output

### ISSUE THREAD

**Issue by tobykurien** [xtext/xtext-gradle-plugin#66]
Currently there seems to be no documented way to disable warnings in the gradle build output, which makes is extremely difficult to spot actual compilation errors in the output (it is interspersed with the warnings). Please provide a way to turn off warnings during compilation.

**Comment by oehme** [comment]
It sounds to me like what you are really looking for is a better way to "skim" the output. We could add color to the log output of Xtext. Would that solve your use case?

I'm asking because I don't think suppressing al warnings is a good idea. Warnings should be taken seriously, as they usually point to a potential runtime problem.

**Comment by tobykurien** [comment]
Colours might partly solve the ability to spot errors, but due to the amount of warnings, errors can easily scroll off past the scroll buffer. Perhaps the ability to turn off specific warnings might help, e.g.: WARNING:List is a raw type. References to generic type List<E> should be parameterized

**Comment by oehme** [comment]
May I ask why there are so many raw type warnings? Are you using some library that forces you to pass raw types? Because generally this warning is correct, using raw types is unsafe.

**Comment by tobykurien** [comment]
So most of those warnings come from using my ```async``` builder (https://github.com/tobykurien/Xtendroid/blob/master/Xtendroid/src/org/xtendroid/utils/AsyncBuilder.xtend#L22). So code like this:

```xtend
async [
  doSomething()
].start()```

Gives the warning, but adding in lambda params:

```xtend
async [a, b|
  doSomething()
].start()```

Removes the warning. Obviously, I prefer to just mute the warnings. There are other warnings too, like deprecation warnings (for older android projects where Google deprecate lots of things often), indentation warnings, unused import warnings, etc. that are just a pain to go back and fix on older projects.

**Comment by oehme** [comment]
That async method returns a raw type. It just needs to be parametrized, then you won't get any warnings in user code.

The Xtext Gradle plugin can already ignore specific warnings, please see the documentation for details.

I'm closing this since I don't believe just switching off all warnings is a good idea.

You can run Gradle with quiet logging if you don't want to see any warnings in general.
